### ISSUE TITLE
IVM 1.3.0 fails to compile

### ISSUE THREAD

**Issue by AlinaNova21** [screeps/driver#24]
https://github.com/screeps/driver/blob/0cd54316c541d60c098bce10565c770ec0abd32b/package.json#L10
There are compilation errors in 1.3.0 that prevent it from being installed, 1.3.1 however, does work.

**Comment by artch** [comment]
1.3.0 compiles quite well for me, could you please elaborate?

**Comment by artch** [comment]
Also, 1.3.0 is the version installed on live servers currently, this is why it is set here.

**Comment by AlinaNova21** [comment]
I'm compiling on alpine in a Docker container, for 1.3.0 I get 
```
make: Entering directory '/screeps/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
In file included from ../src/isolate/class_handle.cc:1:0:
../src/isolate/class_handle.h:23:37: error: expected ')' before 'ptr'
    constexpr CtorFunction(nullptr_t ptr) : fn(ptr), args(0) {} // NOLINT
```

while on 1.3.1 it compiles fine. This may be caused by the newer gcc 5 version that alpine uses, on the debian based node images it fails due to older gcc.
