### ISSUE TITLE
[Beta.8] publicSegments breaks user code

### ISSUE THREAD

**Issue by AlinaNova21** [screeps/driver#25]
In the current ivm betas there is a bug breaking publicSegment lists, it is attempting to run `join(',')` twice, resulting in an error for the second attempt.
https://github.com/screeps/driver/blob/9edc33f46d82f27a672f512700f3bb1d36f4fbe7/lib/runtime/make.js#L266
https://github.com/screeps/driver/blob/9edc33f46d82f27a672f512700f3bb1d36f4fbe7/lib/runtime/runtime.js#L260

I can make a PR if desired, which of the two lines needs to be edited? Currently, on S+ I've just removed `.join(',')` from the `make.js` line, thus solving it.

**Comment by shibdib** [comment]
This is still an issue in the latest beta
