### ISSUE TITLE
Failing to install on ARM

### ISSUE THREAD

**Issue by C0rn3j** [screeps/driver#3]
http://pastebin.com/1KL86m54

The ARM part is probably irrelevant but I am noting it anyways.

**Comment by artch** [comment]
```
make: execvp: g++: Permission denied
```

It seems you have some permission issues.

**Comment by C0rn3j** [comment]
Thanks for pointing out an useful error, I was missing the _gcc_ package.
Perhaps add a compiler to dependencies, if that is possible?

**Comment by artch** [comment]
I don't think it can be considered a specific project dependency, since it is pretty common for modules installed via `npm install` to run `node-gyp` native compiling. You cannot really use `npm install` reliably if you have no `gcc` installed.
