### ISSUE TITLE
env.keys.STATUS_DATA should be env.keys.ROOM_STATUS_DATA

### ISSUE THREAD

**Issue by AlinaNova21** [screeps/driver#42]
The constant for room status data is set here, 

https://github.com/screeps/common/blob/4eaa1f6968787ed213cc22eef6072a5f47ffd052/lib/storage.js#L36

but the wrong constant is used in the driver here:
https://github.com/screeps/driver/blob/e6849f9e2db9495e4344f3ac5d6dd3264e8fb3c6/lib/runtime/data.js#L91
https://github.com/screeps/driver/blob/e6849f9e2db9495e4344f3ac5d6dd3264e8fb3c6/lib/index.js#L514

**Comment by o4kapuk** [comment]
@ags131 should be fixed in [this commit](https://github.com/screeps/driver/commit/1781113dd05e386184997f0b729b96c4e700d9b2) (server version 4.1.11)
